name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

# Cancel previous runs for the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.5.0 # Pin pnpm version

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Lint
        run: make lint

      - name: Run Tests
        run: make test

      - name: Run Build
        run: make build